### ISSUE TITLE
I found a bug using the demo!

### ISSUE THREAD

**Issue by r3dsm0k3** [shapesecurity/shift-fuzzer-js#12]
> Attempted to assign to readonly property.

Here's the module:

``` js
"MS";
export default /[]/iuy;
eval: for ([, {e = /(?:[--])+?/guy, h}, , , ...dsdsycdajfymypo] in aaef) do var m = this; while (typeof this.finally);
import xldlkltgfbttws,  * as kroydd from "UÖõn";
import  * as tgskc from "RÁTN";
```

**Comment by michaelficarra** [comment]
Hmm, I can't reproduce this one either. It looks the same as #11. I wonder if `Attempted to assign to readonly property.` is an error thrown by the browser. @r3dsm0k3 @bounceme What user agent are you using?

I should add the user agent string and possibly a stack trace to the report.

**edit:** See https://github.com/shapesecurity/shift-website/issues/10.

**Comment by r3dsm0k3** [comment]
@michaelficarra  Safari 9.1.2 on OSX 10.11.6.

**Comment by michaelficarra** [comment]
Closing as resolved. See #13 for the resolution.
