### ISSUE TITLE
Library replaces Array.from function with incorrect implementation

### ISSUE THREAD

**Issue by not-an-aardvark** [shapesecurity/shift-fuzzer-js#15]
shift-fuzzer [polyfills the `Array.from` function](https://github.com/shapesecurity/shift-fuzzer-js/blob/c54df674fb69a7a063b79728c14819225cbe3ec1/src/index.js#L25) even in engines where `Array.from` is already present. Additionally, the polyfill seems to be incorrect, which causes very confusing behavior when shift-fuzzer is loaded anywhere in the dependency tree.

```js
// Node 7.8.0

Array.from(new Map([ [ 1, 2 ] ])); // => [ [ 1, 2 ] ]

require('shift-fuzzer');

Array.from(new Map([ [1, 2] ])); // => []
```

**Comment by michaelficarra** [comment]
Oh wow, sorry about that. What a terrible polyfill. See #16.
