### ISSUE TITLE
incorrectly generates numbers in destructuring for-in let bindings

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-fuzzer-js#8]
In [this CI run](https://travis-ci.org/shapesecurity/shift-fuzzer-js/jobs/137151230#L263), a (non-)program including `for(let[591478645587968e1]in{})` was generated.

**Comment by bakkot** [comment]
I've just seen `for(let[this] in .16)`, which I expect is an instance of the same issue.

**Comment by michaelficarra** [comment]
I just hit that one as well: `for (let[this] in /(?:)?/y) {}`.

**Comment by bakkot** [comment]
This is in fact a codegen issue: https://github.com/shapesecurity/shift-codegen-js/issues/57.
