### ISSUE TITLE
I found a bug using the demo!

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-fuzzer-js#9]
> Duplicate export "default"

Here's the code:

``` js
"«";
"ÁßJ";
export {cfbj as pxwlqhle, private as default, lqnmslnirjtql} from ")]:ô";
import s, {lqfkvhshpdmu as knqjeysnxyiwg, eihkyyv} from "À°";
export * from "lR";
import givmiyluihtlnrk, {tlcyovhdv, aijukgcgwnyn, xtbnhcaykjha} from "Ñ";
export default class ahwqthir {
  set [new function r(e, h, b) {
    "use strict";
  }(2e308.catch |= arguments)] (bytmspmpkokj) {
    "use strict";
    var e = new.target;
    const y = true;
    try {} finally {}
    return;
    ;
  }
  static get [class c extends "" {}]() {
    "use strict";
    try {} catch (r) {} finally {}
    switch (typeof null) {
      case "óH":
      default:
    }
    {}
  }
  static set [vmpxuffhxqac] (udw) {
    "use strict";
    const t = new.target;
    while (this()) switch (null) {
      default:
    }
    class o {
      static set [false] (n) {}
    }
    debugger;
    ;
  }
  set [!2e308] (wgonyyd) {
    "Å^Û[";
    "@rî";
    "ÔV";
    "";
    "¶";
    "use strict";
    null;
    try {} catch (m) {}
    ;
    ugkajuwdwhyawju: i: break ugkajuwdwhyawju;
    while (0) new.target;
  }
  static get [null.catch |= ``]() {
    "";
    "use strict";
    "use strict";
    "use strict";
    {}
    while ("æÔ") throw null;
    throw /[(-\,\ucdf7-\uDA80\xad)*]/my();
    let r;
    for (this();; class {}) for (var t of eval) continue;
  }
}
```

**Comment by bakkot** [comment]
Odd - this looks like a duplicate of #2, which the fuzzer demo is [supposed to avoid](https://github.com/shapesecurity/shift-website/blob/dfa0c10c37c00d5c39a4613cb31a58e0d5d0d496/js/fuzzer/main.js#L51).

**Comment by michaelficarra** [comment]
Yeah, that is strange. I've reproduced this several times, though. I'm going to break point it in the error function and see what's going on.

**edit:** Well, that didn't work. We're generating a _lot_ of programs with duplicate bindings...

**Comment by bakkot** [comment]
> We're generating a lot of programs with duplicate bindings...

Consequence of trying to use interesting names when possible. Suggest instead waiting for a test to fail and then storing the AST generated, then running that through the error-testing function. (I'll do this myself if I get a minute.)

**Comment by michaelficarra** [comment]
It turns out we're filtering the early errors during generation but not the parser errors thrown during confirmation. That will be a bit trickier to fix because we'll have to go back to generating programs at that point.

**Comment by bakkot** [comment]
We're filtering out the errors returned by the validator, which (in theory) includes early errors. The issue is that the validator on the demo is passing `let a; export default 0; export {a as default}`, but the parser (iff early errors are enabled) is not. I think this is a difference between the validator and the parser in the demo.

``` js
let f = = `let a; export default 0; export {a as default}`;
validator.Validator.validate(parser.parseModule(f, {earlyErrors: false})); // = []
parser.parseModule(f); // throws
```

**Comment by bakkot** [comment]
Ideally the validator used online would just use the version of the early error checker exported by the version of the parser online, instead of duplicating the parser, but I don't know how to make cjsify do that.

**Comment by michaelficarra** [comment]
Do we just need to update the validator? Surely it is fixed in a more recent version than what is available on the website.

**Comment by bakkot** [comment]
After [shift-website#8](https://github.com/shapesecurity/shift-website/pull/8), the validator give the correct error and `knownErrors` returns true for the code above. I think this can be closed as a duplicate of #2, but I'm going to let the fuzzer run for a while first.

**Comment by michaelficarra** [comment]
I've been doing the same 😄.

**Comment by michaelficarra** [comment]
Closing. Looks to be fixed.
